[project]
name = "MindMesh"
version = "0.1.0"
description = "MindMesh is an intelligent AI platform that connects, analyzes, and summarizes information from across the web."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
